export type ServiceType = {
  id: string;
  service: string;
  provider_type: string;
  request_details: string;
  verification_notes: string;
  availability: string;
  payment_type: string;
  request_type: string;
  category: 'agriculture' | 'veterinary' | 'health' | 'events' | 'facilities' | 'construction' | 'security' | 'training';
  icon: string;
};

export const SERVICE_TYPES: ServiceType[] = [
  {
    id: 'farm-mechanization',
    service: 'Farm Mechanization',
    provider_type: 'Mechanization Providers',
    request_details: 'Plowing, planting, harvesting; schedule by farm size/crop',
    verification_notes: 'Verified operator; GPS tracking optional; vehicle/maintenance badge',
    availability: 'Location-based',
    payment_type: 'Escrow via Banda Wallet / AgriPay',
    request_type: 'Instant or Scheduled',
    category: 'agriculture',
    icon: 'Tractor',
  },
  {
    id: 'crop-monitoring',
    service: 'Crop Monitoring & Advisory',
    provider_type: 'Agronomists / Crop Specialists',
    request_details: 'Soil testing, pest/disease checks, irrigation guidance',
    verification_notes: 'Certified agronomist; progress report delivered',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'agriculture',
    icon: 'Sprout',
  },
  {
    id: 'livestock-health',
    service: 'Livestock Health & Veterinary',
    provider_type: 'Veterinarians / Animal Health Providers',
    request_details: 'Vaccinations, AI, disease treatment, emergency care',
    verification_notes: 'Veterinary license + Good Conduct certificate verified',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Instant or Scheduled',
    category: 'veterinary',
    icon: 'Stethoscope',
  },
  {
    id: 'farm-labor',
    service: 'Farm Labor / Workers',
    provider_type: 'Farm Labor Providers',
    request_details: 'Temporary/seasonal labor for planting/harvesting',
    verification_notes: 'Identity verified; availability & rating shown',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'agriculture',
    icon: 'Users',
  },
  {
    id: 'equipment-rental-farm',
    service: 'Equipment Rental (Farm)',
    provider_type: 'Farm Equipment Providers',
    request_details: 'Tractors, sprayers, irrigation tools; hourly/daily',
    verification_notes: 'Ownership verified; maintenance badge',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Instant or Scheduled',
    category: 'agriculture',
    icon: 'Wrench',
  },
  {
    id: 'fisheries-support',
    service: 'Fisheries Support Services',
    provider_type: 'Fisheries Technicians / Aquaculture Experts',
    request_details: 'Fish pond management, feed supply, water quality monitoring',
    verification_notes: 'Verified expertise; licenses if required',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'agriculture',
    icon: 'Fish',
  },
  {
    id: 'veterinary-consultation',
    service: 'Veterinary Consultation',
    provider_type: 'Licensed Veterinarians',
    request_details: 'Farm visits, treatment plans, animal care advice',
    verification_notes: 'License & Good Conduct verified',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Instant or Scheduled',
    category: 'veterinary',
    icon: 'HeartPulse',
  },
  {
    id: 'scheduled-vaccinations',
    service: 'Scheduled Vaccinations & AI',
    provider_type: 'Veterinary Technicians',
    request_details: 'Scheduled vaccination or artificial insemination',
    verification_notes: 'License verified; history logged in app',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'veterinary',
    icon: 'Syringe',
  },
  {
    id: 'emergency-animal-care',
    service: 'Emergency Animal Care',
    provider_type: 'Vets / Para-Vets',
    request_details: 'Urgent on-demand visits for sick/injured livestock',
    verification_notes: 'Verified provider; GPS tracking optional',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Instant',
    category: 'veterinary',
    icon: 'Ambulance',
  },
  {
    id: 'health-screening',
    service: 'Health Screening',
    provider_type: 'Health Workers / Clinics',
    request_details: 'On-site checkups, preventive health advice, optional teleconsultation',
    verification_notes: 'License/certification verified',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'health',
    icon: 'Activity',
  },
  {
    id: 'first-aid-emergency',
    service: 'First Aid / Emergency Support',
    provider_type: 'Certified Health Providers',
    request_details: 'Rapid response to farm or community emergencies',
    verification_notes: 'Verified provider with equipment',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Instant',
    category: 'health',
    icon: 'Cross',
  },
  {
    id: 'equipment-rental-events',
    service: 'Equipment Rental (Events)',
    provider_type: 'Event / Equipment Providers',
    request_details: 'Sound systems, generators, projectors; delivery optional',
    verification_notes: 'Verified ownership & condition',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Instant or Scheduled',
    category: 'events',
    icon: 'Music',
  },
  {
    id: 'event-setup-catering',
    service: 'Event Setup / Catering',
    provider_type: 'Catering / Event Management',
    request_details: 'Food preparation, service, venue setup',
    verification_notes: 'Verified provider; service rating visible',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'events',
    icon: 'UtensilsCrossed',
  },
  {
    id: 'maintenance-repair',
    service: 'Maintenance / Repair',
    provider_type: 'Maintenance Providers',
    request_details: 'Plumbing, electrical, carpentry, building repair',
    verification_notes: 'Identity verified; past work photos optional',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Instant or Scheduled',
    category: 'facilities',
    icon: 'Hammer',
  },
  {
    id: 'cleaning-sanitation',
    service: 'Cleaning & Sanitation',
    provider_type: 'Facilities Providers',
    request_details: 'Residential, farm, office, or event cleaning',
    verification_notes: 'Verified provider; service rating visible',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'facilities',
    icon: 'Sparkles',
  },
  {
    id: 'pest-control',
    service: 'Pest Control & Environmental Services',
    provider_type: 'Pest Control Companies',
    request_details: 'Rodent, insect, or crop pest management',
    verification_notes: 'Certified/licensed provider',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'facilities',
    icon: 'Bug',
  },
  {
    id: 'construction-modernization',
    service: 'Construction & Modernization',
    provider_type: 'Contractors / Engineers',
    request_details: 'Building, renovation, or farm modernization projects',
    verification_notes: 'Verified credentials; past work portfolio',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'construction',
    icon: 'HardHat',
  },
  {
    id: 'surveying-services',
    service: 'Surveying Services',
    provider_type: 'Surveyors / GIS Technicians',
    request_details: 'Land measurement, mapping, soil analysis',
    verification_notes: 'Licensed surveyor; verified reports',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'construction',
    icon: 'MapPin',
  },
  {
    id: 'surveillance-security',
    service: 'Surveillance & Security',
    provider_type: 'Security Providers',
    request_details: 'CCTV installation, farm perimeter monitoring, guard services',
    verification_notes: 'Verified security provider; background-checked',
    availability: 'Location-based',
    payment_type: 'Escrow',
    request_type: 'Instant or Scheduled',
    category: 'security',
    icon: 'Shield',
  },
  {
    id: 'agricultural-training',
    service: 'Agricultural Training',
    provider_type: 'Agronomists / Farm Experts',
    request_details: 'Crop management workshops, farm best practices',
    verification_notes: 'Certified trainers; attendance logged',
    availability: 'Location-based or Remote',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'training',
    icon: 'GraduationCap',
  },
  {
    id: 'livestock-veterinary-training',
    service: 'Livestock & Veterinary Training',
    provider_type: 'Veterinarians / Animal Experts',
    request_details: 'On-site or online training for animal care',
    verification_notes: 'Verified license; training history logged',
    availability: 'Location-based or Remote',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'training',
    icon: 'BookOpen',
  },
  {
    id: 'business-technical-training',
    service: 'Business & Technical Skills Training',
    provider_type: 'Business Consultants / Technical Trainers',
    request_details: 'Entrepreneurship, financial management, equipment operation',
    verification_notes: 'Certified trainers; verified modules',
    availability: 'Location-based or Remote',
    payment_type: 'Escrow',
    request_type: 'Scheduled',
    category: 'training',
    icon: 'Briefcase',
  },
];

export const SERVICE_CATEGORIES = [
  { id: 'agriculture', name: 'Agriculture', icon: 'Tractor' },
  { id: 'veterinary', name: 'Veterinary', icon: 'Stethoscope' },
  { id: 'health', name: 'Health', icon: 'HeartPulse' },
  { id: 'events', name: 'Events', icon: 'Music' },
  { id: 'facilities', name: 'Facilities', icon: 'Building' },
  { id: 'construction', name: 'Construction', icon: 'HardHat' },
  { id: 'security', name: 'Security', icon: 'Shield' },
  { id: 'training', name: 'Training', icon: 'GraduationCap' },
] as const;

export function getServicesByCategory(category: string): ServiceType[] {
  return SERVICE_TYPES.filter((service) => service.category === category);
}

export function getServiceById(id: string): ServiceType | undefined {
  return SERVICE_TYPES.find((service) => service.id === id);
}
