export type ServiceLevel = 'Basic' | 'Skilled' | 'Expert' | 'Master';
export type ServiceMode = 'Individual' | 'Team' | 'Company';
export type BookingMode = 'Hourly' | 'Daily' | 'Project' | 'Contract';
export type RiskLevel = 'Low' | 'Medium' | 'High';

export interface ServiceMetadata {
  serviceType: ServiceMode;
  skillLevel: ServiceLevel;
  certificationRequired: boolean;
  licenseRequired: boolean;
  riskLevel: RiskLevel;
  serviceAreaCoverage: string[];
  bookingMode: BookingMode[];
  toolsProvidedBy: 'Client' | 'Provider' | 'Both';
  insuranceRequired: boolean;
  backgroundCheckStatus: 'Pending' | 'Completed' | 'Verified';
  adminApprovalStatus: 'Pending' | 'Approved' | 'Rejected';
  lockedFields?: string[];
}

export interface ServiceSpecialization {
  id: string;
  parentCategory: string;
  category: string;
  subCategory?: string;
  specialization?: string;
  icon: string;
  metadata: Partial<ServiceMetadata>;
}

export const LABOR_SKILLS_TAXONOMY: ServiceSpecialization[] = [
  {
    id: 'agri-land-prep-tractor',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Land Preparation Services',
    subCategory: 'Tractor Operator',
    icon: 'Tractor',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'agri-land-prep-ploughing',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Land Preparation Services',
    subCategory: 'Ploughing Services',
    icon: 'Tractor',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: false,
      licenseRequired: false,
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: false,
    },
  },
  {
    id: 'agri-land-prep-harrowing',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Land Preparation Services',
    subCategory: 'Harrowing Services',
    icon: 'Tractor',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-land-prep-ridging',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Land Preparation Services',
    subCategory: 'Ridging Services',
    icon: 'Tractor',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-land-clearing-manual',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Land Preparation Services',
    subCategory: 'Land Clearing (Manual)',
    icon: 'Axe',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Basic',
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Both',
    },
  },
  {
    id: 'agri-land-clearing-mechanized',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Land Preparation Services',
    subCategory: 'Land Clearing (Mechanized)',
    icon: 'Bulldozer',
    metadata: {
      serviceType: 'Company',
      skillLevel: 'Expert',
      licenseRequired: true,
      riskLevel: 'High',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'agri-soil-testing',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Land Preparation Services',
    subCategory: 'Soil Testing Technicians',
    icon: 'TestTube',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'Low',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-crop-planting',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Crop Production Services',
    subCategory: 'Planting Services',
    icon: 'Sprout',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Basic',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'agri-crop-transplanting',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Crop Production Services',
    subCategory: 'Transplanting Services',
    icon: 'Sprout',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Skilled',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'agri-crop-weeding-manual',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Crop Production Services',
    subCategory: 'Weeding Services (Manual)',
    icon: 'Hand',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Basic',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'agri-crop-weeding-herbicide',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Crop Production Services',
    subCategory: 'Herbicide Application',
    icon: 'Spray',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'High',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'agri-fertilizer-application',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Crop Production Services',
    subCategory: 'Fertilizer Application',
    icon: 'Package',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-crop-spraying',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Crop Production Services',
    subCategory: 'Crop Spraying Services',
    icon: 'Spray',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'High',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'agri-drone-spraying',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Crop Production Services',
    subCategory: 'Drone Spraying Operators',
    icon: 'Drone',
    metadata: {
      serviceType: 'Company',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'High',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'agri-irrigation-drip-install',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Irrigation Services',
    subCategory: 'Drip Irrigation Setup',
    icon: 'Droplet',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-irrigation-sprinkler',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Irrigation Services',
    subCategory: 'Sprinkler Installation',
    icon: 'Shower',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-irrigation-pump',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Irrigation Services',
    subCategory: 'Pump Installation & Maintenance',
    icon: 'Wrench',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Project', 'Contract'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-irrigation-scheduling',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Irrigation Services',
    subCategory: 'Irrigation Scheduling Services',
    icon: 'Calendar',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'Low',
      bookingMode: ['Contract'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-water-management',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Irrigation Services',
    subCategory: 'Water Management Consultancy',
    icon: 'Droplet',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'Low',
      bookingMode: ['Project', 'Contract'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-harvesting-labor',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Harvest & Post-Harvest Services',
    subCategory: 'Harvesting Labor',
    icon: 'Users',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Basic',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'agri-threshing',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Harvest & Post-Harvest Services',
    subCategory: 'Threshing Services',
    icon: 'Wheat',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-shelling',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Harvest & Post-Harvest Services',
    subCategory: 'Shelling Services',
    icon: 'Package',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Basic',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-drying',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Harvest & Post-Harvest Services',
    subCategory: 'Drying Services',
    icon: 'Sun',
    metadata: {
      serviceType: 'Company',
      skillLevel: 'Skilled',
      riskLevel: 'Low',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-sorting-grading',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Harvest & Post-Harvest Services',
    subCategory: 'Sorting & Grading Services',
    icon: 'Filter',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Skilled',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'agri-storage-handling',
    parentCategory: 'Agriculture & Farm Services',
    category: 'Harvest & Post-Harvest Services',
    subCategory: 'Storage & Post-Harvest Handling',
    icon: 'Warehouse',
    metadata: {
      serviceType: 'Company',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Contract'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'livestock-handling-herding',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Livestock Services',
    subCategory: 'Animal Handling & Herding',
    icon: 'Cow',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Contract'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'livestock-ai',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Livestock Services',
    subCategory: 'Artificial Insemination (AI)',
    icon: 'Syringe',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Hourly', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'livestock-health-tech',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Livestock Services',
    subCategory: 'Animal Health Technicians',
    icon: 'Stethoscope',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Hourly', 'Daily'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'livestock-milking',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Livestock Services',
    subCategory: 'Milking Services',
    icon: 'Milk',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Contract'],
      toolsProvidedBy: 'Both',
    },
  },
  {
    id: 'livestock-feed-formulation',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Livestock Services',
    subCategory: 'Feed Formulation Services',
    icon: 'Package',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'Low',
      bookingMode: ['Project', 'Contract'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'poultry-farm-attendant',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Poultry Services',
    subCategory: 'Poultry Farm Attendants',
    icon: 'Bird',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Contract'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'poultry-brooding',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Poultry Services',
    subCategory: 'Brooding Management',
    icon: 'Egg',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Contract'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'poultry-vaccination',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Poultry Services',
    subCategory: 'Vaccination Services',
    icon: 'Syringe',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'poultry-hatchery',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Poultry Services',
    subCategory: 'Hatchery Management',
    icon: 'Egg',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Contract'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'poultry-biosecurity',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Poultry Services',
    subCategory: 'Biosecurity Services',
    icon: 'Shield',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Project', 'Contract'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'aqua-pond-construction',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Aquaculture Services',
    subCategory: 'Pond Construction Labor',
    icon: 'Waves',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Skilled',
      riskLevel: 'High',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Both',
    },
  },
  {
    id: 'aqua-fish-stocking',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Aquaculture Services',
    subCategory: 'Fish Stocking Services',
    icon: 'Fish',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Low',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'aqua-feeding-management',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Aquaculture Services',
    subCategory: 'Feeding Management',
    icon: 'Package',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Contract'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'aqua-water-quality',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Aquaculture Services',
    subCategory: 'Water Quality Monitoring',
    icon: 'Droplet',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'Low',
      bookingMode: ['Project', 'Contract'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'aqua-harvesting',
    parentCategory: 'Livestock, Poultry & Aquaculture Services',
    category: 'Aquaculture Services',
    subCategory: 'Fish Harvesting Services',
    icon: 'Fish',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Skilled',
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Both',
    },
  },
  {
    id: 'construction-masonry',
    parentCategory: 'Construction & Building Services',
    category: 'Skilled Construction Labor',
    subCategory: 'Masonry',
    icon: 'Brick',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Both',
    },
  },
  {
    id: 'construction-carpentry',
    parentCategory: 'Construction & Building Services',
    category: 'Skilled Construction Labor',
    subCategory: 'Carpentry',
    icon: 'Hammer',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'construction-plumbing',
    parentCategory: 'Construction & Building Services',
    category: 'Skilled Construction Labor',
    subCategory: 'Plumbing',
    icon: 'Wrench',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Hourly', 'Daily', 'Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'construction-electrical',
    parentCategory: 'Construction & Building Services',
    category: 'Skilled Construction Labor',
    subCategory: 'Electrical Installation',
    icon: 'Zap',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'High',
      bookingMode: ['Hourly', 'Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'construction-welding',
    parentCategory: 'Construction & Building Services',
    category: 'Skilled Construction Labor',
    subCategory: 'Welding & Fabrication',
    icon: 'Flame',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'High',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'construction-tiling',
    parentCategory: 'Construction & Building Services',
    category: 'Skilled Construction Labor',
    subCategory: 'Tiling Services',
    icon: 'Grid',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'construction-excavator',
    parentCategory: 'Construction & Building Services',
    category: 'Heavy Construction Operators',
    subCategory: 'Excavator Operators',
    icon: 'Construction',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'High',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'construction-bulldozer',
    parentCategory: 'Construction & Building Services',
    category: 'Heavy Construction Operators',
    subCategory: 'Bulldozer Operators',
    icon: 'Construction',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'High',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'construction-crane',
    parentCategory: 'Construction & Building Services',
    category: 'Heavy Construction Operators',
    subCategory: 'Crane Operators',
    icon: 'Crane',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'High',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'construction-painting',
    parentCategory: 'Construction & Building Services',
    category: 'Finishing & Fit-Out',
    subCategory: 'Painting Services',
    icon: 'Paintbrush',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'mechanical-equipment-operator',
    parentCategory: 'Mechanical, Technical & Engineering Services',
    category: 'Machinery Services',
    subCategory: 'Equipment Operators',
    icon: 'Settings',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'High',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'mechanical-maintenance-tech',
    parentCategory: 'Mechanical, Technical & Engineering Services',
    category: 'Machinery Services',
    subCategory: 'Machinery Maintenance Technicians',
    icon: 'Wrench',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Hourly', 'Daily', 'Contract'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'mechanical-tractor-mechanic',
    parentCategory: 'Mechanical, Technical & Engineering Services',
    category: 'Mechanical Repair',
    subCategory: 'Tractor Mechanics',
    icon: 'Wrench',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Hourly', 'Daily'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'mechanical-generator-tech',
    parentCategory: 'Mechanical, Technical & Engineering Services',
    category: 'Mechanical Repair',
    subCategory: 'Generator Technicians',
    icon: 'Zap',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      riskLevel: 'High',
      bookingMode: ['Hourly', 'Daily'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'electrical-solar-installation',
    parentCategory: 'Mechanical, Technical & Engineering Services',
    category: 'Electrical & Energy',
    subCategory: 'Solar Installation Technicians',
    icon: 'Sun',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'High',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'water-borehole-drilling',
    parentCategory: 'Water, Sanitation & Environmental Services',
    category: 'Water Services',
    subCategory: 'Borehole Drilling Crew',
    icon: 'Droplet',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'High',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'water-pump-installation',
    parentCategory: 'Water, Sanitation & Environmental Services',
    category: 'Water Services',
    subCategory: 'Pump Installation Teams',
    icon: 'Wrench',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'sanitation-fumigation',
    parentCategory: 'Water, Sanitation & Environmental Services',
    category: 'Environmental Management',
    subCategory: 'Fumigation Services',
    icon: 'Spray',
    metadata: {
      serviceType: 'Company',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'High',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'transport-truck-driver',
    parentCategory: 'Transport, Logistics & Operations',
    category: 'Transport Services',
    subCategory: 'Truck Drivers',
    icon: 'Truck',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: false,
      licenseRequired: true,
      riskLevel: 'High',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'transport-machinery-driver',
    parentCategory: 'Transport, Logistics & Operations',
    category: 'Transport Services',
    subCategory: 'Heavy Machinery Drivers',
    icon: 'Construction',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'High',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'logistics-loading',
    parentCategory: 'Transport, Logistics & Operations',
    category: 'Logistics Support',
    subCategory: 'Loading & Offloading Labor',
    icon: 'Package',
    metadata: {
      serviceType: 'Team',
      skillLevel: 'Basic',
      riskLevel: 'Medium',
      bookingMode: ['Hourly', 'Daily'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'events-sound-engineer',
    parentCategory: 'Events, Seminars & Public Services',
    category: 'Event Services',
    subCategory: 'Sound Engineers',
    icon: 'Music',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      riskLevel: 'Low',
      bookingMode: ['Hourly', 'Daily'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'events-lighting-tech',
    parentCategory: 'Events, Seminars & Public Services',
    category: 'Event Services',
    subCategory: 'Lighting Technicians',
    icon: 'Lightbulb',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      riskLevel: 'Medium',
      bookingMode: ['Hourly', 'Daily'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'hospitality-chef',
    parentCategory: 'Hospitality, Tourism & Wildlife Services',
    category: 'Hospitality Services',
    subCategory: 'Chefs & Cooks',
    icon: 'ChefHat',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'Low',
      bookingMode: ['Hourly', 'Daily', 'Contract'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'hospitality-catering',
    parentCategory: 'Hospitality, Tourism & Wildlife Services',
    category: 'Hospitality Services',
    subCategory: 'Catering Services',
    icon: 'UtensilsCrossed',
    metadata: {
      serviceType: 'Company',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'Low',
      bookingMode: ['Project'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'tourism-tour-guide',
    parentCategory: 'Hospitality, Tourism & Wildlife Services',
    category: 'Tourism & Wildlife',
    subCategory: 'Tour Guides',
    icon: 'Map',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'Low',
      bookingMode: ['Hourly', 'Daily'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'office-data-entry',
    parentCategory: 'Office, Corporate & Professional Services',
    category: 'Office Support',
    subCategory: 'Data Entry Clerks',
    icon: 'Keyboard',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Basic',
      riskLevel: 'Low',
      bookingMode: ['Hourly', 'Daily', 'Contract'],
      toolsProvidedBy: 'Client',
    },
  },
  {
    id: 'professional-accountant',
    parentCategory: 'Office, Corporate & Professional Services',
    category: 'Professional Services',
    subCategory: 'Accountants',
    icon: 'Calculator',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'Low',
      bookingMode: ['Hourly', 'Contract'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'professional-bookkeeper',
    parentCategory: 'Office, Corporate & Professional Services',
    category: 'Professional Services',
    subCategory: 'Bookkeepers',
    icon: 'BookOpen',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'Low',
      bookingMode: ['Hourly', 'Contract'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'health-community-worker',
    parentCategory: 'Health, Veterinary & Community Services',
    category: 'Health Services',
    subCategory: 'Community Health Workers',
    icon: 'HeartPulse',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Skilled',
      certificationRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Daily', 'Contract'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'veterinary-vet',
    parentCategory: 'Health, Veterinary & Community Services',
    category: 'Veterinary Services',
    subCategory: 'Veterinarians',
    icon: 'Stethoscope',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: true,
      licenseRequired: true,
      riskLevel: 'Medium',
      bookingMode: ['Hourly', 'Daily'],
      toolsProvidedBy: 'Provider',
      insuranceRequired: true,
    },
  },
  {
    id: 'tech-software-dev',
    parentCategory: 'Technology, Data & Research Services',
    category: 'Technology Services',
    subCategory: 'Software Developers',
    icon: 'Code',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Expert',
      certificationRequired: false,
      riskLevel: 'Low',
      bookingMode: ['Hourly', 'Project', 'Contract'],
      toolsProvidedBy: 'Provider',
    },
  },
  {
    id: 'research-field-enumerator',
    parentCategory: 'Technology, Data & Research Services',
    category: 'Research & Survey',
    subCategory: 'Field Enumerators',
    icon: 'ClipboardList',
    metadata: {
      serviceType: 'Individual',
      skillLevel: 'Basic',
      riskLevel: 'Low',
      bookingMode: ['Daily', 'Project'],
      toolsProvidedBy: 'Provider',
    },
  },
];

export const SERVICE_PARENT_CATEGORIES = [
  { id: 'agriculture', name: 'Agriculture & Farm Services', icon: 'Tractor' },
  { id: 'livestock', name: 'Livestock, Poultry & Aquaculture Services', icon: 'Cow' },
  { id: 'construction', name: 'Construction & Building Services', icon: 'HardHat' },
  { id: 'mechanical', name: 'Mechanical, Technical & Engineering Services', icon: 'Settings' },
  { id: 'water-sanitation', name: 'Water, Sanitation & Environmental Services', icon: 'Droplet' },
  { id: 'transport', name: 'Transport, Logistics & Operations', icon: 'Truck' },
  { id: 'events', name: 'Events, Seminars & Public Services', icon: 'Calendar' },
  { id: 'hospitality', name: 'Hospitality, Tourism & Wildlife Services', icon: 'Hotel' },
  { id: 'office', name: 'Office, Corporate & Professional Services', icon: 'Briefcase' },
  { id: 'health', name: 'Health, Veterinary & Community Services', icon: 'HeartPulse' },
  { id: 'technology', name: 'Technology, Data & Research Services', icon: 'Laptop' },
] as const;

export function getServicesByParentCategory(parentCategory: string): ServiceSpecialization[] {
  return LABOR_SKILLS_TAXONOMY.filter((service) => service.parentCategory === parentCategory);
}

export function getServiceById(id: string): ServiceSpecialization | undefined {
  return LABOR_SKILLS_TAXONOMY.find((service) => service.id === id);
}

export function getServiceCategories(parentCategory: string): string[] {
  const services = getServicesByParentCategory(parentCategory);
  return [...new Set(services.map((s) => s.category))];
}

export function getServiceSubCategories(parentCategory: string, category: string): string[] {
  const services = getServicesByParentCategory(parentCategory).filter(
    (s) => s.category === category
  );
  return [...new Set(services.map((s) => s.subCategory).filter(Boolean))] as string[];
}
